version: '1'
services:
  db:
    #    container_name: my_db
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=change-me
      - MYSQL_DB=mysql
    ports:
      - 3306:3306
  app:
    build: .
    environment:
      spring.datasource.url: jdbc:mysql://localhost:3306/yet?createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: change-me
    depends_on:
      - db
    ports:
      - "8080:8080"
    links:
      - db
volumes:
  db:
    driver: local